## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
attrition_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   Department                1470 non-null   object
 4   DistanceFromHome          1470 non-null   int64 
 5   Education                 1470 non-null   int64 
 6   EducationField            1470 non-null   object
 7   EnvironmentSatisfaction   1470 non-null   int64 
 8   HourlyRate                1470 non-null   int64 
 9   JobInvolvement            1470 non-null   int64 
 10  JobLevel                  1470 non-null   int64 
 11  JobRole                   1470 non-null   object
 12  JobSatisfaction           1470 non-null   int64 
 13  MaritalStatus             1470 non-null   object
 14  NumCompaniesWorked      

In [4]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[["Attrition", "Department"]]
y_df

Attrition              Department
0          Yes                   Sales
1           No  Research & Development
2          Yes  Research & Development
3           No  Research & Development
4           No  Research & Development
...        ...                     ...
1465        No  Research & Development
1466        No  Research & Development
1467        No  Research & Development
1468        No                   Sales
1469        No  Research & Development

[1470 rows x 2 columns]

In [5]:
attrition_df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [6]:
# Create a list of at least 10 column names to use as X data
columns_to_X = ['Age', 'BusinessTravel', 'DistanceFromHome',
       'Education', 'EducationField', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']


# Create X_df using your selected columns
X_df = attrition_df[columns_to_X]

# Show the data types for X_df
X_df.dtypes

Age                          int64
BusinessTravel              object
DistanceFromHome             int64
Education                    int64
EducationField              object
EnvironmentSatisfaction      int64
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
NumCompaniesWorked           int64
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [7]:
X_df["BusinessTravel"].value_counts()

BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

In [8]:
X_df["EducationField"].value_counts()

EducationField
Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Human Resources      27
Name: count, dtype: int64

In [9]:
X_df["JobRole"].value_counts()

JobRole
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64

In [10]:
X_df["MaritalStatus"].value_counts()

MaritalStatus
Married     673
Single      470
Divorced    327
Name: count, dtype: int64

In [11]:
X_df["OverTime"].value_counts()

OverTime
No     1054
Yes     416
Name: count, dtype: int64

In [12]:
y_df["Department"].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [13]:
y_df["Attrition"].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [14]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size = 0.2, random_state = 42)

In [15]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
ohe = OneHotEncoder(sparse_output=False)
le = LabelEncoder()

columns_to_convert_dummy = ["BusinessTravel", "EducationField", "JobRole", "MaritalStatus"]
columns_to_convert_le = ["OverTime"]

In [16]:
def create_dummies(dataframe, column):
    # Transform the column using get_dummies()
    dummy_columns = pd.get_dummies(dataframe[column], dtype = "int")
    # Concatenate the dummy_columns onto the original dataframe, and delete the original column that was dummied
    dataframe = pd.concat([dataframe, dummy_columns], axis = 1).drop(columns = column)
    return dataframe

In [17]:
X_train = create_dummies(X_train, columns_to_convert_dummy)

In [18]:
X_test = create_dummies(X_test, columns_to_convert_dummy)

In [19]:
X_train['OverTime'] = le.fit_transform(X_train['OverTime'])

In [20]:
X_test['OverTime'] = le.fit_transform(X_test['OverTime'])

In [21]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1176 entries, 1097 to 1126
Data columns (total 42 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1176 non-null   int64
 1   DistanceFromHome                   1176 non-null   int64
 2   Education                          1176 non-null   int64
 3   EnvironmentSatisfaction            1176 non-null   int64
 4   HourlyRate                         1176 non-null   int64
 5   JobInvolvement                     1176 non-null   int64
 6   JobLevel                           1176 non-null   int64
 7   JobSatisfaction                    1176 non-null   int64
 8   NumCompaniesWorked                 1176 non-null   int64
 9   OverTime                           1176 non-null   int64
 10  PercentSalaryHike                  1176 non-null   int64
 11  PerformanceRating                  1176 non-null   int64
 12  RelationshipSatisfacti

In [22]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
print(X_train_scaled)

[[-1.38855944  1.44039645 -0.86335572 ...  1.8451272  -0.93733358
  -0.66288195]
 [-2.04073779 -0.52269928 -0.86335572 ... -0.54196806 -0.93733358
   1.50856422]
 [-0.84507748  1.31770296 -0.86335572 ...  1.8451272  -0.93733358
  -0.66288195]
 ...
 [-1.60595222 -0.76808624  1.06322176 ... -0.54196806  1.06685604
  -0.66288195]
 [-0.84507748  0.45884859 -0.86335572 ... -0.54196806  1.06685604
  -0.66288195]
 [ 1.43754676 -0.03192534  0.09993302 ... -0.54196806  1.06685604
  -0.66288195]]


In [23]:
# Create a OneHotEncoder for the Department column
dept_encoder = OneHotEncoder(sparse_output = False)

# Fit the encoder to the training data
y_train_dept = y_train["Department"].values.reshape(-1, 1)
dept_encoded = dept_encoder.fit(y_train_dept)

# Create two new variables by applying the encoder
# to the training and testing data
y_train_dept_encoded = dept_encoder.transform(y_train_dept)
y_test_dept_encoded = dept_encoder.transform(y_test["Department"].values.reshape(-1, 1))
print(y_train_dept_encoded)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# Create a OneHotEncoder for the Attrition column
attr_encoder = OneHotEncoder(sparse_output = False)

# Fit the encoder to the training data
y_train_attr = y_train["Attrition"].values.reshape(-1, 1)
attr_encoded = attr_encoder.fit(y_train_attr)

# Create two new variables by applying the encoder
# to the training and testing data
y_train_attr_encoded = attr_encoder.transform(y_train_attr)
y_test_attr_encoded = attr_encoder.transform(y_test["Attrition"].values.reshape(-1, 1))
print(y_train_attr_encoded)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]


## Create, Compile, and Train the Model

In [25]:
# Find the number of columns in the X training data
X_train.shape[1]

# Create the input layer
input_layer = layers.Input(shape=(X_train.shape[1],), name='input_features')

# Create at least two shared layers
shared_layer1 = layers.Dense(64, activation='relu', name = 'shared_layer1')(input_layer)
shared_layer2 = layers.Dense(128, activation='relu', name = 'shared_layer2')(shared_layer1)

In [26]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
dept_layer1 = layers.Dense(32, activation='relu', name = 'dept_layer_hidden')(shared_layer2)

# Create the output layer
dept_output_layer = layers.Dense(3, activation = "softmax", name="dept_output")(dept_layer1)

In [27]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attr_layer1 = layers.Dense(32, activation='relu', name = 'attr_layer_hidden')(shared_layer2)

# Create the output layer
attr_output_layer = layers.Dense(2, activation = "sigmoid", name="attr_output")(attr_layer1)

In [28]:
# Create the model
model = Model(inputs=input_layer, outputs=[dept_output_layer, attr_output_layer])

# Compile the model
model.compile(optimizer='adam',
              loss={'dept_output': 'categorical_crossentropy', 'attr_output': 'binary_crossentropy'},
              metrics={'dept_output': 'accuracy', 'attr_output': 'accuracy'})

# Summarize the model
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_features (InputLayer  [(None, 42)]                 0         []                            
 )                                                                                                
                                                                                                  
 shared_layer1 (Dense)       (None, 64)                   2752      ['input_features[0][0]']      
                                                                                                  
 shared_layer2 (Dense)       (None, 128)                  8320      ['shared_layer1[0][0]']       
                                                                                                  
 dept_layer_hidden (Dense)   (None, 32)                   4128      ['shared_layer2[0][0]']   

In [29]:
# Train the model
model.fit(
    X_train_scaled,
    {
        'dept_output': y_train_dept_encoded,
        'attr_output': y_train_attr_encoded,
    },
    epochs=50,
    batch_size=32,
    validation_split=0.2
)


Epoch 1/50
30/30 [==============================] - 5s 26ms/step - loss: 1.2538 - dept_output_loss: 0.7178 - attr_output_loss: 0.5361 - dept_output_accuracy: 0.6947 - attr_output_accuracy: 0.7830 - val_loss: 0.9875 - val_dept_output_loss: 0.4770 - val_attr_output_loss: 0.5104 - val_dept_output_accuracy: 0.8432 - val_attr_output_accuracy: 0.7966
Epoch 2/50
30/30 [==============================] - 0s 4ms/step - loss: 0.6841 - dept_output_loss: 0.2664 - attr_output_loss: 0.4177 - dept_output_accuracy: 0.9383 - attr_output_accuracy: 0.8404 - val_loss: 0.6427 - val_dept_output_loss: 0.1768 - val_attr_output_loss: 0.4659 - val_dept_output_accuracy: 0.9280 - val_attr_output_accuracy: 0.7966
Epoch 3/50
30/30 [==============================] - 0s 5ms/step - loss: 0.4763 - dept_output_loss: 0.0984 - attr_output_loss: 0.3779 - dept_output_accuracy: 0.9755 - attr_output_accuracy: 0.8404 - val_loss: 0.5416 - val_dept_output_loss: 0.1000 - val_attr_output_loss: 0.4416 - val_dept_output_accuracy: 0.9

In [30]:
print(X_train_scaled.shape)
print(y_train_dept_encoded.shape)
print(y_train_attr_encoded.shape)

(1176, 42)
(1176, 3)
(1176, 2)


In [31]:
# Evaluate the model with the testing data
test_results = model.evaluate(X_test_scaled, {'dept_output': y_test_dept_encoded, 'attr_output': y_test_attr_encoded})
test_results

10/10 [==============================] - 0s 5ms/step - loss: 1.2780 - dept_output_loss: 0.0990 - attr_output_loss: 1.1789 - dept_output_accuracy: 0.9694 - attr_output_accuracy: 0.8299


[1.277982234954834,
 0.09904977679252625,
 1.1789324283599854,
 0.9693877696990967,
 0.8299319744110107]

In [32]:
# Print the accuracy for both department and attrition
print(f"Department predictions accuracy: {test_results[3]}")
print(f"Attrition predictions accuracy: {test_results[4]}")

Department predictions accuracy: 0.9693877696990967
Attrition predictions accuracy: 0.8299319744110107


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Accuracy may not be the best metric for this data because we have an imbalanced dataset. A balanced accuracy metric may be a better tool to minimize any bias.
2. Since there were 3 options for Department, I used softmax given that this activation function will provide a better probability across the 3 options. Since Attrition only had 2 binary choices, I used sigmoid there.
3. I would like to eliminate **variables** in my X dataframe that are highly correlated (e.g., Years in Current Role and Years since Last Promotion). I would also play with the **parameters** in the model (e.g., crossentropy type, activation function, validation mix, etc.). Finally, adding **more data** (without overfitting the model) would hopefully provide more accuracy as well.